# Obtener organización gestora de cada zona regulada
PREFIX edintzone: <http://vocab.linkeddata.es/datosabiertos/def/common/zone#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?zona ?organizacion
WHERE {
    ?zona rdf:type ?tipoZona .
    ?tipoZona rdfs:subClassOf* edintzone:RegulatedZone .
    ?zona edintzone:managedBy ?organizacion .
}
ORDER BY ?tipoZona ?zona ?organizacion

# Obtener zona, tipo y organización con nombres
PREFIX edintzone: <http://vocab.linkeddata.es/datosabiertos/def/common/zone#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?zona ?tipoZona ?organizacion ?nombreOrg
WHERE {
    ?zona rdf:type ?tipoZona .
    ?tipoZona rdfs:subClassOf* edintzone:RegulatedZone .
    ?zona edintzone:managedBy ?organizacion .
    OPTIONAL { ?organizacion rdfs:label ?nombreOrg . }
}
ORDER BY ?tipoZona ?zona ?nombreOrg
