# Obtener entidades administrativas que componen cada zona
PREFIX edintzone: <http://vocab.linkeddata.es/datosabiertos/def/common/zone#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?zona ?tipoZona ?entidad ?nombreEntidad
WHERE {
    ?zona rdf:type ?tipoZona .
    ?tipoZona rdfs:subClassOf* edintzone:RegulatedZone .
    ?zona edintzone:composedOf ?entidad .
    OPTIONAL { ?entidad rdfs:label ?nombreEntidad . }
}
ORDER BY ?zona ?entidad

# Obtener entidades administrativas que componen cada zona con nombres de zona
PREFIX edintzone: <http://vocab.linkeddata.es/datosabiertos/def/common/zone#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?zona ?nombreZona ?tipoZona ?entidad ?nombreEntidad
WHERE {
    ?zona rdf:type ?tipoZona .
    ?tipoZona rdfs:subClassOf* edintzone:RegulatedZone .
    OPTIONAL { ?zona rdfs:label ?nombreZona . }
    ?zona edintzone:composedOf ?entidad .
    OPTIONAL { ?entidad rdfs:label ?nombreEntidad . }
}
ORDER BY ?nombreZona ?nombreEntidad
